title: Harish Senthilkumar
logo: assets/img/IMG_4011.jpg
description: Data Scientist and AI/Machine Learning Engineer
show_downloads: true
theme: jekyll-theme-cayman
includes:
  - assets/img/css/style.css
class="site-logo"
